[package]
name = "ui3-core"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-sys = "0.3.51"
js-sys = "0.3.51"
wasm-bindgen = "0.2.74"